version: "3.9"
services:
  comfyui:
    image: nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
    container_name: comfyui
    restart: unless-stopped
    shm_size: "2g"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../data/models:/workspace/ComfyUI/models
      - ../workflows:/workspace/workflows
      - ../data/output:/workspace/output
    ports:
      - "8188:8188"
    command: >
      bash -lc "
      apt-get update &&
      apt-get install -y python3.10 python3.10-venv git wget unzip &&
      update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1 &&
      cd /workspace &&
      git clone https://github.com/comfyanonymous/ComfyUI.git || true &&
      cd ComfyUI &&
      python -m venv .venv &&
      . .venv/bin/activate &&
      pip install --upgrade pip &&
      pip install --extra-index-url https://download.pytorch.org/whl/cu121 torch torchvision torchaudio &&
      pip install -r requirements.txt &&
      python main.py --listen 0.0.0.0 --port 8188 --output-directory /workspace/output
      "
